// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUPKz9XlpPXLzCL0SJdqzDhrtaxViRnWw',
    appId: '1:527977638458:web:f567dc95284ac78b1b6303',
    messagingSenderId: '527977638458',
    projectId: 'mentorme-79853',
    authDomain: 'mentorme-79853.firebaseapp.com',
    storageBucket: 'mentorme-79853.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLP_di3qvidgRJ_wyZG7NbAmkseHSC1eg',
    appId: '1:527977638458:android:a3d17ddb26eac2e31b6303',
    messagingSenderId: '527977638458',
    projectId: 'mentorme-79853',
    storageBucket: 'mentorme-79853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnskhJSunYn1Ul2ZpRKjgpolQFd_VCOLA',
    appId: '1:527977638458:ios:2a84e9f0693638e61b6303',
    messagingSenderId: '527977638458',
    projectId: 'mentorme-79853',
    storageBucket: 'mentorme-79853.firebasestorage.app',
    iosBundleId: 'com.example.mentorme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnskhJSunYn1Ul2ZpRKjgpolQFd_VCOLA',
    appId: '1:527977638458:ios:2a84e9f0693638e61b6303',
    messagingSenderId: '527977638458',
    projectId: 'mentorme-79853',
    storageBucket: 'mentorme-79853.firebasestorage.app',
    iosBundleId: 'com.example.mentorme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUPKz9XlpPXLzCL0SJdqzDhrtaxViRnWw',
    appId: '1:527977638458:web:2b4635cb2841841a1b6303',
    messagingSenderId: '527977638458',
    projectId: 'mentorme-79853',
    authDomain: 'mentorme-79853.firebaseapp.com',
    storageBucket: 'mentorme-79853.firebasestorage.app',
  );
}
